create table if not exists public.rolling_updates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  payload jsonb not null
);

create index if not exists rolling_updates_created_at_idx
  on public.rolling_updates (created_at desc);

create table if not exists public.daily_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  trigger text not null,
  created_at timestamptz not null default now(),
  payload jsonb not null
);

create index if not exists daily_snapshots_snapshot_date_idx
  on public.daily_snapshots (snapshot_date desc);

alter publication supabase_realtime add table public.rolling_updates;
alter publication supabase_realtime add table public.daily_snapshots;

alter table public.rolling_updates enable row level security;
alter table public.daily_snapshots enable row level security;

create policy "Allow public read rolling updates"
on public.rolling_updates
for select
to anon, authenticated
using (true);

create policy "Allow public read daily snapshots"
on public.daily_snapshots
for select
to anon, authenticated
using (true);
